### ISSUE TITLE
Medical Staff Survey  - feedback for the face shields

### ISSUE THREAD

**Issue by thomasd538** [Charlotte-MEDI/Faceshields#13]
Folks,
We need to create a quick survey for medical personnel so we can get feedback on the face shields.
What do we think of the four following questions?   Please make suggestions.

Did the faces shield work as intended?
yes
not
If not, why not.

Did the face shield break while you were using it?
yes
no
If so, what happen?

How comfortable is the mask?
1 to 10  (1 - painful)  (10 - comfortable)

Do you have any suggestions?

**Comment by JeremyProffitt** [comment]
Looks good, platform?  Survey Monkey?  Perhaps we print out slips of paper with a short url to use to get to the survey as well?

**Comment by DavidCTaylorPhD** [comment]
Google form is easy and free. Also, it opens into a spreadsheet with data charts.

**Comment by JeremyProffitt** [comment]
That sounds great!

Should we add what version 1 or 2 they prefer?

**Comment by stoph** [comment]
When are we going to ask these questions? Seems like am initial questionnaire when they get the masks (first impressions) then a follow-up survey a few days later to see how they are holding up/if anything broke.

Also, can we expect to get feedback directly from the users, or should we try to get a point of contact within each group (head nurse, etc) to solicit feedback for us?

**Comment by thomasd538** [comment]
I  was hoping to have the nurses fill out survey Monday night after using the facemaks for aday.

Our point of contact  right now is Jean and Julie Chai who are both doctors and help start this

**Comment by thomasd538** [comment]
Good suggestion on asking about the version they like.  I will also update shield so they can identify if they are using 1 or 2.

**Comment by DavidCTaylorPhD** [comment]
Tom, did you start a survey or do you want me to begin working on it?

**Comment by DavidCTaylorPhD** [comment]
https://docs.google.com/forms/d/1f1yQcWOaGO_e_ZMt9W13Po1ughF1EaBVwzVy3lqsi9k/edit?usp=sharing

The link above is to a survey I just created.

**Comment by JeremyProffitt** [comment]
We should maybe have them share pictures of what does not work??

**Comment by DavidCTaylorPhD** [comment]
I can see if that is an option. I do like this idea, Jeremy.

**Comment by DavidCTaylorPhD** [comment]
Jeremy, You can have people attach images, but you have to have a gmail account. What do you think?

**Comment by DavidCTaylorPhD** [comment]
[`Feedback Survey`](https://docs.google.com/forms/d/1f1yQcWOaGO_e_ZMt9W13Po1ughF1EaBVwzVy3lqsi9k/edit?usp=sharing)

**Comment by tjfagan** [comment]
I am going to close this issue because there is two threads, follow the below link for the new thread.

https://github.com/tjfagan/Faceshields/issues/19
