### ISSUE TITLE
Determine life of virus on various surfaces used

### ISSUE THREAD

**Issue by stoph** [Charlotte-MEDI/Faceshields#6]

**Comment by stoph** [comment]
The current thinking is that it "may persist on surfaces for a few hours or up to several days" [Source](https://www.who.int/news-room/q-a-detail/q-a-coronaviruses)

**Comment by horvath112** [comment]
https://www.sciencedaily.com/releases/2020/03/200320192755.htm

"two to three days on plastic"

**Comment by stoph** [comment]
We had some good times helping save the world.

**Comment by thomasd538** [comment]
Yes, we didSent from my iPhoneOn Feb 23, 2023, at 10:55 AM, Christoph Khouri ***@***.***> wrote:﻿
We had some good times helping save the world.
